frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use app\models\Data;
use common\models\ContactUs;
use frontend\models\Country;
use frontend\models\forms\AnalyzeForm;
use frontend\models\forms\VoiceForm;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\helpers\Json;
use yii\helpers\VarDumper;
use yii\web\UploadedFile;
use yii\authclient\AuthAction;
use yii\base\InvalidArgumentException;
use frontend\models\Auth;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use app\models\User;
use frontend\widgets\ProcessingResultsWidget\ProcessingResultsWidget;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'save-voice' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => AuthAction::class,
                'successCallback' => [$this, 'successCallback']
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionTest()
    {
        return $this->render('test', []);
    }

    public function actionNotify()
    {

    }

    public function actionSaveVoice()
    {
        $model = new VoiceForm();

        if (Yii::$app->request->isPost && $model->load(Yii::$app->request->post())) {

            $model->file = UploadedFile::getInstance($model, 'file');

            if ($model->validate()) {
                $model->file->saveAs('uploads/' . $model->filename);
            }
        }

        //TODO: extract features

        return Json::encode([
            'data' => $_POST,
            'html' => ProcessingResultsWidget::widget([]),
        ]);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new AnalyzeForm();

        $model->load(Yii::$app->request->get());

        return $this->render('index', ['model' => $model,]);
    }

    /**
     * Displays workspace.
     *
     * @return mixed
     */
    public function actionWorkspace()
    {
        return $this->render('workspace');
    }

    /**
     * Displays privacy-policy.
     *
     * @return mixed
     */
    public function actionPrivacyPolicy()
    {
        return $this->render('privacy-policy');
    }

    /**
     * Displays result page.
     *
     * @return mixed
     */
    public function actionResult()
    {
        $model = new AnalyzeForm();

        $model->load(Yii::$app->request->get());

        return $this->render('result', ['model' => $model,]);
    }


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/');
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactUs();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail']) && $model->save()) {
                Yii::$app->session->setFlash('success', "Thank
                                        you! Your message has been sent. We'll get back to you as soon as possible.");
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }
            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * user Data upload page.
     *
     * @return mixed
     */
    public function actionAddData()
    {
        if (!Yii::$app->user->isGuest) {

            $model = new Data();
            if ($model->load(Yii::$app->request->post())) {
                $model->uploadFile = UploadedFile::getInstance($model, 'uploadFile');
                $fileName = rand(0, 99) . $model->uploadFile;


                $model->file = $fileName;
                $model->user_id = Yii::$app->getUser()->identity->getId();
                $model->created_at = time();
                $model->updated_at = time();
                $model->raw_data = '';
                $model->partner_id = 0;
                $model->uploadFile->saveAs(Yii::getAlias('@webroot') . '/uploads/' . $fileName);
                $model->save(false);
                if ($model->uploadFile->extension == 'xls' || $model->uploadFile->extension == 'xlsx') {
                    $objPHPExcel = \PHPExcel_IOFactory::load(Yii::getAlias('@webroot') . '/uploads/' . $model->file);
//                echo "<pre>";
//                print_r($objPHPExcel->getActiveSheet()->toArray(null, true, true, true));
                    $data = $objPHPExcel->getActiveSheet()->toArray(null, true, true, true);
                    $model->raw_data = json_encode($data);
                    $model->save(false);
                } else {
                    $data = file_get_contents(Yii::getAlias('@webroot') . '/uploads/' . $model->file);
                    $model->raw_data = json_encode($data);
                    $model->save(false);
                }

            }
            $model->uploadFile = '';

            $files = $model->find()->where(['user_id' => Yii::$app->getUser()->identity->getId()])->all();
            return $this->render('add_data', [
                'model' => $model,
                'files' => $files
            ]);
        }
    }

    public function actionDeleteFile()
    {
        $id = Yii::$app->request->get('id');
        $model = Data::findOne($id);
        if (file_exists(Yii::getAlias('@webroot') . '/uploads/' . $model->file)) {
            unlink(Yii::getAlias('@webroot') . '/uploads/' . $model->file);
        }
        $model->delete();
        return $this->redirect('add-data');
    }

    /**
     * user Profile page.
     *
     * @return mixed
     */
    public function actionProfile()
    {
        if (!Yii::$app->user->isGuest) {
            $model = User::findOne(Yii::$app->user->identity->getId());
            $countries = Country::find()->all();
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                $model->birthday = date("Y-m-d", strtotime($model->birthday));
                $model->city = ucfirst($model->city);
                $model->save();
                Yii::$app->session->setFlash('success', 'Update user data');
            }
            $model->birthday = date('d-m-Y', strtotime($model->birthday));
            return $this->render('profile', [
                'model' => $model,
                'countries' => $countries
            ]);
        } else {
            return $this->goHome();
        }
    }

    public function successCallback($client)
    {
        $attributes = $client->getUserAttributes();

        $auth = User::find()->where(['email' => $attributes['email'], 'source' => $attributes['id']])->one();
        if (Yii::$app->user->isGuest) {
            if (!empty($auth) && Yii::$app->user->login($auth)) { // login
                $this->redirect(['site/profile']);
            } else { // signup
                if (User::find()->where(['email' => $attributes['email']])->exists()) {
                    Yii::$app->getSession()->setFlash('error', [
                        Yii::t('app', "User with the same email as in {client} account already exists but isn't linked to it. Login using email first to link it.", ['client' => $client->getTitle()]),
                    ]);
                } else {
                    $password = Yii::$app->security->generateRandomString(6);
                    if (isset($attributes['name']['givenName']) && isset($attributes['name']['familyName'])) {
                        $user = new User([

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:ageprocessor.com" content="ageprocessor.com">
    <meta property="og:Age Processor" content="Age Processor">
    <meta name="yandex-verification" content="7a0cb79ae3b89180" />
    <link href="/favicon.png" rel="icon" type="image/x-icon">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-153636318-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-153636318-1');
    </script>

</head>
<body>
<?php $this->beginBody() ?>


<!--   --><?php
//    NavBar::begin([
//        'brandLabel' => '</span>Life<span class="tracker">tracker</span>',
//        'brandUrl' => Yii::$app->homeUrl,
//        'options' => [
//            'class' => 'navbar-inverse navbar-fixed-top',
//        ],
//    ]);
//    $menuItems = [
//        ['label' => 'Home', 'url' => ['/site/index']],
//        ['label' => 'About', 'url' => ['/site/about']],
//        ['label' => 'Contact', 'url' => ['/site/contact']],
//    ];
//    if (Yii::$app->user->isGuest) {
//        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
//        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
//    } else {
//        $menuItems[] = ['label' => 'Profile', 'url' => ['/site/profile']];
//        $menuItems[] = ['label' => 'Data', 'url' => ['/site/add-data']];
//        $menuItems[] = '<li>'
//            . Html::beginForm(['/site/logout'], 'post')
//            . Html::submitButton(
//                'Logout (' . Yii::$app->user->identity->email . ')',
//                ['class' => 'btn btn-link logout']
//            )
//            . Html::endForm()
//            . '</li>';
//    }
//    echo Nav::widget([
//        'options' => ['class' => 'navbar-nav navbar-right'],
//        'items' => $menuItems,
//    ]);
//    NavBar::end();
//    ?>
<nav class="navbar center-block nav-block">
    <div class=" header_content">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navMobile">
                <span class="" style="color:black"> <img style="    margin-top: 12px;" src="/img/elements/bars.svg"></span>

            </button>
            <a class="navbar-brand header_logo" href="/">   <img src="/img/logo.svg">
            </a>
        </div>
        <div class="collapse navbar-collapse menu" id="navMobile" style="height: 0">
            <ul class="nav navbar-nav navbar-right ">
                <li><a href="/site/contact">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="/site/privacy-policy">Privacy Policy</a></li>
            </ul>

        </div>
    </div>
</nav>
<!--        --><?//= Alert::widget() ?>
        <?= $content ?>

<!--Bottom-->
<div class="bottom_content">
    <div class="menu_bottom" style="margin-top: 100px;">
        <div class="header_logo" style="    margin-top: 15px">
            <a href="#">
                <img class="desctop_logo" src="/img/logo.svg">
                <img class="table_logo" src="/img/Mini.svg">
            </a>
        </div>
        <div class="menu menu-bottom" style="">
            <ul>
                <li><a href="#">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul>
        </div>
    </div>
</div>

<!--Bottom end -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>